server:
  port: 2021
spring:
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: false
  # Just a fix for redis session error that came up.
  session:
    store-type: none

afro:
  pixels:
    datasource:
      primary:
        url: jdbc:mysql://localhost:3306/afro_pixels?useSSL=false&createDatabaseIfNotExists=True
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: password
        max:
          connection:
            pool-size: '40'
    liquibase:
      enable: false
      changelog: classpath:config/liquibase/index.xml
    jpa:
      packages-to-scan: com.jworks
      hibernate:
        show-sql: false
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL55Dialect
    jwt:
      secret: secret
      expiration-period-milli-seconds: 999999
